### ISSUE TITLE
Segment display show Speed

### ISSUE THREAD

**Issue by Scruck83** [simelation/simhub-plugins#6]
Congratulations on the plugin, very good job, but, it would be nice to add the speed of the cars in the segments displays.

**Comment by lukester1975** [comment]
Heh, yeah that is a good point that is missing, isn't it? I'm just starting on making the segment displays configurable a bit (for now just ordering / moving between sides) but will add in speed.

More generic "do anything" configuration like other dashes will take a bit longer...

Thanks.

**Comment by Scruck83** [comment]
I am a slimax manager user and I would like to find many options of it in this plugin. If you need to test, I offer you my help

**Comment by lukester1975** [comment]
To be honest, I don't really know what SLIMaxManager provides - I never liked the UI and once Fanaleds became available, that's what I used.

So probably easiest if you just request any specific features you'd like to see. I can't promise anything though! Fundamentally, I'd like to see the plugin staying quite simple, otherwise I'll confuse myself like trying to use SliMaxManager :)

Thanks for the testing offer. Can I ask if you have SLI-F1 or Pro? I have a Pro and had an F1 on loan, but it is returned now. So certainly testing with an F1 could be helpful.

**Comment by Scruck83** [comment]
I have sli-pro, slimax manager the interface is complicated to see and configure and if I can see options that I like in this plugin, I make sure that I choose this plugin.

**Comment by lukester1975** [comment]
Should now be there in 0.9.0.
